theme: jekyll-theme-cayman
title: "Hello there, I'm **@DamienLegros** ! :smiley_cat:"
description: "Student finishing a Master 2 of Artificial Intelligence and Computational Biology at Sorbonne Université, Paris :school:"

plugins:
  - jemoji
